/* App.svelte generated by Svelte v3.41.0 */
import { create_ssr_component, escape } from "svelte/internal";

let name = "world";

const App = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  return `<h1>Hello ${escape(name)}!</h1>`;
});

export default App;
